/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;
import Modelo.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author yeffr
 */
public class frm_actualizarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frm_actualizarUsuario
     */
    public frm_actualizarUsuario() {
        initComponents();
        rrellenarCmb();
    }
    
    public static void rrellenarCmb()
    {
        try
        {
          Statement stm = Modelo.Conexion.conectar().createStatement();
          ResultSet rs = stm.executeQuery("Select * From Personas join Usuarios"
                  + " on Personas.IdPersonas=Usuarios.IdPersona");
          
          while(rs.next())
          {
              cmbuser_update1.addItem(rs.getString("Usuario"));
          }
          stm.close();
          rs.close();
        }
        catch(SQLException ex)
        {
          JOptionPane.showMessageDialog(null,ex.getMessage());  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelupdateuser = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        cmbRol = new javax.swing.JComboBox<>();
        txtPass = new javax.swing.JPasswordField();
        jLabel23 = new javax.swing.JLabel();
        lblguardar2 = new javax.swing.JLabel();
        cmbuser_update1 = new javax.swing.JComboBox<>();
        txtuser = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        lblATRAS = new javax.swing.JLabel();
        jhdjh = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        panelupdateuser.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Password");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Nombre");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Usuario");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Rol");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("Direccion");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Apellido");

        txtnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(51, 51, 51));

        txtApellido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(51, 51, 51));

        txtDireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(51, 51, 51));

        cmbRol.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Administrador" }));

        jLabel23.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel23.setText("Actualizar Usuario");

        lblguardar2.setBackground(new java.awt.Color(255, 255, 255));
        lblguardar2.setIcon(new javax.swing.ImageIcon("D:\\Mayo-Agosto\\Programacion1\\SistemaEventos\\img\\editar.png")); // NOI18N
        lblguardar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblguardar2MouseClicked(evt);
            }
        });

        cmbuser_update1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbuser_update1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbuser_update1ItemStateChanged(evt);
            }
        });

        txtuser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtuser.setForeground(new java.awt.Color(51, 51, 51));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Usuario");

        lblATRAS.setIcon(new javax.swing.ImageIcon("D:\\Mayo-Agosto\\Programacion1\\SistemaEventos\\img\\atras.png")); // NOI18N
        lblATRAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblATRASMouseClicked(evt);
            }
        });
        lblATRAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblATRASKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelupdateuserLayout = new javax.swing.GroupLayout(panelupdateuser);
        panelupdateuser.setLayout(panelupdateuserLayout);
        panelupdateuserLayout.setHorizontalGroup(
            panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelupdateuserLayout.createSequentialGroup()
                .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelupdateuserLayout.createSequentialGroup()
                        .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelupdateuserLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelupdateuserLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17))
                        .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelupdateuserLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(lblguardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelupdateuserLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelupdateuserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jhdjh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)))
                    .addGroup(panelupdateuserLayout.createSequentialGroup()
                        .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelupdateuserLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel22)))
                            .addGroup(panelupdateuserLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblATRAS)))
                        .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelupdateuserLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbuser_update1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelupdateuserLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel23)))))
                .addContainerGap())
        );
        panelupdateuserLayout.setVerticalGroup(
            panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelupdateuserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(lblATRAS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jhdjh, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelupdateuserLayout.createSequentialGroup()
                        .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbuser_update1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(91, 91, 91)
                        .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(32, 32, 32)
                        .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(33, 33, 33)
                        .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(panelupdateuserLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelupdateuserLayout.createSequentialGroup()
                                .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(panelupdateuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(lblguardar2)))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelupdateuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelupdateuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblguardar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblguardar2MouseClicked
        
        int Id =0;
        
        
          try
        {
          Statement stm = Modelo.Conexion.conectar().createStatement();
          ResultSet rs = stm.executeQuery("Select IdPersonas \n" +
"From Usuarios INNER JOIN Personas on Personas.IdPersonas=Usuarios.IdPersona \n" +
"  WHERE Usuario='"+cmbuser_update1.getSelectedItem().toString()+"'");
          
          
          while(rs.next())
          {
              Id=rs.getInt("IdPersonas");
          }
          
        }
          catch(SQLException ex)
          {
              JOptionPane.showMessageDialog(null,ex.getMessage()); 
          }
        Usuarios user = new Usuarios();
         Administrador admin = new Administrador();
        
        if(cmbRol.getSelectedIndex()==0)
        {
            Portero p = new Portero();
            admin._mantenimientoPersona = new Modelo.mantenimientoPortero();
            
            p.setNombre(txtnombre.getText());
            p.setApellido(txtApellido.getText());
            p.setDireccion(txtDireccion.getText());
            p.setUsuario(txtuser.getText());
            p.setRol("Portero");
            p.setPassword(txtPass.getText());
            
            if(admin._mantenimientoPersona.actualizarPersona(Id,p))
            { 
            JOptionPane.showMessageDialog(null,"Portero Actualizado Exitosamente");
            this.setVisible(false);
            user.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Portero No existe"); 
                this.setVisible(false);
            user.setVisible(true);
            }
        }
        
        else if(cmbRol.getSelectedIndex()==1)
        {
             Administrador p = new Administrador();
            admin._mantenimientoPersona = new Modelo.mantenimientoAdministrador();
            
            p.setNombre(txtnombre.getText());
            p.setApellido(txtApellido.getText());
            p.setDireccion(txtDireccion.getText());
            p.setUsuario(txtuser.getText());
            p.setRol("Adminitrador");
            p.setPassword(txtPass.getPassword().toString());
            
            if(admin._mantenimientoPersona.actualizarPersona(Id,p))
            {
            JOptionPane.showMessageDialog(null,"Administrador Actualizado Exitosamente");
            
            
            this.setVisible(false);
            user.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Administrador No existe");
            this.setVisible(false);
            user.setVisible(true);
            }
            
                    
        }
        
        
        
    }//GEN-LAST:event_lblguardar2MouseClicked

    private void cmbuser_update1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbuser_update1ItemStateChanged
        
        
        try
        {
          Statement stm = Modelo.Conexion.conectar().createStatement();
          ResultSet rs = stm.executeQuery("Select NombrePersona,Apellido,Descripcion_direccion,Rol,Usuario,Contraseña\n" +
"From Personas\n" +
"jOIN \n" +
"Usuarios ON Personas.IdPersonas=Usuarios.IdPersona\n" +
"WHERE Usuario='"+cmbuser_update1.getSelectedItem().toString()+"'");
          
          while(rs.next())
          {
              System.out.print(rs.getNString("NombrePersona"));
              txtnombre.setText(rs.getNString("NombrePersona"));
              txtApellido.setText(rs.getNString("Apellido"));
              txtDireccion.setText(rs.getNString("Descripcion_direccion"));
              if(rs.getString("Rol").equals("Portero"))
              {
                  cmbRol.setSelectedIndex(0);
              }
              else
              {
                  cmbRol.setSelectedIndex(1);
              }
          
              txtuser.setText(rs.getNString("Usuario"));
              txtPass.setText(rs.getNString("Contraseña"));
          }
          stm.close();
          rs.close();
        }
        catch(SQLException ex)
        {
          JOptionPane.showMessageDialog(null,ex.getMessage());  
        }
        
        
        
    }//GEN-LAST:event_cmbuser_update1ItemStateChanged

    private void lblATRASKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblATRASKeyPressed
       
                                         
      Usuarios user = new Usuarios();
      this.setVisible(false);
      user.setVisible(true);
        
    }//GEN-LAST:event_lblATRASKeyPressed

    private void lblATRASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblATRASMouseClicked
        // TODO add your handling code here:
       Usuarios user = new Usuarios();
      this.setVisible(false);
      user.setVisible(true);
        
    }//GEN-LAST:event_lblATRASMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_actualizarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbRol;
    private static javax.swing.JComboBox<String> cmbuser_update1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jhdjh;
    private javax.swing.JLabel lblATRAS;
    private javax.swing.JLabel lblguardar2;
    private javax.swing.JPanel panelupdateuser;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
